### ISSUE TITLE
wish: integration with graalvm

### ISSUE THREAD

**Issue by nahuel** [wizawu/tyrian#11]
It will be nice to use 1c to generate typings for Java libraries but use graalvm (with all his node support https://www.graalvm.org/docs/reference-manual/languages/js/ ) instead of nashorn.

**Comment by wizawu** [comment]
I have been watching GraalVM for a while and surely it's one of the candidates of the next JVM for 1c. Currently I am evaluating Hotspot(mainly JDK 10 and 11), OpenJ9 and GraalVM from 3 aspects:
* Compatibility with Java
* Compatibility with Node and TypeScript
* Performance
Maybe we can see GraalVM in the next major release (1c v9).

**Comment by wizawu** [comment]
1. The multithreading in Graal JavaScript is quite different from Nashorn. And I have to say Nashorn provide a more pleasant way to do it.
    * graalvm/graaljs#30
    * [Multithreading](https://github.com/graalvm/graaljs/blob/master/docs/user/NashornMigrationGuide.md#multithreading)

2. With Graal JavaScript, it's more like running Node.js in another engine (than v8) where we can import Java classes. Unfortunately, there is significant overhead when our program is mainly built on Java libraries.

3. Currently, _1c_  is still aimed to developing **JVM** programs in **TypeScript**, and Nashorn provides better performance and accessibility for that.

**Comment by wizawu** [comment]
It's done. You can choose either nashorn or graaljs as runtime.
