### ISSUE TITLE
What is the Plan for 1c and Nashorn Deprecation?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [wizawu/tyrian#17]
Given that nashorn is deprecated and apparently on its way out of the JDK is there a migration plan for 1c to something else?

**Comment by wizawu** [comment]
Probably graalvm. I would decide it by the end of Jan 2020. Any suggestions are appreciated :smile:

**Comment by mfreeman-xtivia** [comment]
So how would that work? From what I understand of GraalVM the java side and the node/JS side run in 2 different processes

**Comment by wizawu** [comment]
You can try
```
bin/node --jvm
```
within the graalvm release. It has pretty much the same API as nashorn. For example,
```
Packages.java.lang.System.out.println("ok")
```

**Comment by wizawu** [comment]
Sorry it's delayed for an entire year.
Please check out https://www.npmjs.com/package/tyrian/v/9.0.0-beta.1

**Comment by mfreeman-xtivia** [comment]
FYI all of your links to GitHub Pages on the main landing page for this repo are broken and generate 404s

**Comment by wizawu** [comment]
Thank you for noticing. I just switched the domain to [tyrian.wizawu.com](https://tyrian.wizawu.com/). I would redirect 1c.wizawu.com to it later.
