### ISSUE TITLE
1c is little bit misleading

### ISSUE THREAD

**Issue by arcanist123** [wizawu/tyrian#24]
Hi.

Just for your information - the name 1c is the name of one of the biggest IT companies in russia. the offer a huge range of products for enterprise software and the whole programming language 1c script. if you package is going to be popular, you might get legal actions from them. 

This is not actually an issue for me - just something you might want to consider

Regards

**Comment by wizawu** [comment]
You're right. At first place I didn't know about the company 1c. And the 1c I named means "1 compiler for all".
Recently I am thinking change its name to something more related to typescript, such as "ti", "tx", "t...".
Thank you for your notice.

**Comment by talesmgodois** [comment]
I didn't like much the name either. But I loved the idea of the project. Have you tried use this to run a webserver or generate a war file?


Best.

**Comment by wizawu** [comment]
I might simply name it `toj`. What do you think?

**Comment by talesmgodois** [comment]
what about `typeJ` ot `Jtype` or `t2j` ( Like Type to Java)?

**Comment by apws** [comment]
hi, +tyrian still finds milions of results on google and half milion on bing )) .... consider +tygrix ))
