### ISSUE TITLE
Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by mojo2012** [wizawu/tyrian#27]
Version 9.0.5 outputs the following warnings on several commans like `tyrian init`.
```
(node:32160) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32160) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```

**Comment by wizawu** [comment]
https://github.com/antlr/antlr4/issues/2834

It says the issue had been fixed in antlr4@4.9, but if there's another bug in 4.9 you just mentioned days ago. Let's just go with 4.8 by now. I will follow antlr4's updates.
