### ISSUE TITLE
Provide better way to import java types

### ISSUE THREAD

**Issue by mojo2012** [wizawu/tyrian#28]
It would be awesome if we could support a syntax like this for using java types, instead of the current way:
```typescript
import { System } from "java.lang"

System.out.println("Test");
```

Is there a way to use the graalvm way `var FileClass = Java.type("java.io.File");` and combine it with the autogenerated declarations? Instead of declaring the classes we could use interfaces and load the implementations as recommended by graalvm.

**Comment by wizawu** [comment]
> import { System } from "java.lang"

This syntax is common in node.js. I considered it before, but it can be conflicted with npm packages, e.g.,
```
import { FooBar }  from "socket.io"
```
As for

```
var FileClass = Java.type("java.io.File")
```
I believe it's already supported.

**Comment by mojo2012** [comment]
The problem with `const FileClass = Java.type("java.io.File")` is that is has no type!
I think there is little chance that a generated java import would conflict with a real typescript import.
Almost all java libraries adhere to the reverse domain name notation (except for java.*, javax.*): `io.testlab.app.*).
I've never encountered a JS/TS library that had such a package name.

**Comment by rjmunro** [comment]
To be sure to avoid conflicts, you could prefix with something like:

```typescript
import { System } from "jvm:java.lang"
```

**Comment by wizawu** [comment]
https://github.com/wizawu/tyrian/wiki/II.-Manual#3-import-java-classes
