### ISSUE TITLE
Official web site: Chrome Privacy Error

### ISSUE THREAD

**Issue by altPOCA** [wizawu/tyrian#31]
Your connection is not private
Attackers might be trying to steal your information from tyrian.wizawu.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by wizawu** [comment]
<img width="506" alt="DeepinScreenshot_select-area_20210613151105" src="https://user-images.githubusercontent.com/1676756/121798555-a3f79700-cc59-11eb-9eb7-3d96404528e6.png">

It's odd... The certification should be provided by GitHub. I don't know why there is a stuck.

**Comment by altPOCA** [comment]
> <img alt="DeepinScreenshot_select-area_20210613151105" width="506" src="https://user-images.githubusercontent.com/1676756/121798555-a3f79700-cc59-11eb-9eb7-3d96404528e6.png">
> 
> It's odd... The certification should be provided by GitHub. I don't know why there is a stuck.

More information:

This server could not prove that it is tyrian.wizawu.com; its security certificate expired 4 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Sunday, June 13, 2021. Does that look right? If not, you should correct your system's clock and then refresh this page.

Proceed to tyrian.wizawu.com (unsafe)

**Comment by altPOCA** [comment]
The date on my system is absolutely right. I used a VPN service to access your site. The same error. It's something wrong with your site, not us.

**Comment by wizawu** [comment]
I never serve this site on my own. It's completely on GitHub Page.

**Comment by wizawu** [comment]
I've reported it to GitHub. We can just wait.

**Comment by wizawu** [comment]
The SSL problem is fixed now. Thanks for notice!
