### ISSUE TITLE
[Feature Request] Expose internal functions as a library module

### ISSUE THREAD

**Issue by Egoscio-zz** [wizawu/tyrian#8]
The 1c command-line interface is a very handy tool to get started fast, however, I believe that it'll also be great to expose internal functions such as jar disassembly as importable modules. eg:

```typescript
import { parseJar, buildDefinition } from "1c";

buildDefinition("./lib/@types/a.d.ts", parseJar("./lib/a.jar"));
```

That way, developers can extend upon the features provided in 1c in their own applications or libraries.

Thank you.

**Comment by wizawu** [comment]
Yeah, that would be useful. I didn't expect that there would be _developers_ so soon. I will add it to the roadmap.
